// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: kynno/rewardshare/v1/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// MsgRegisterRewardshare defines a message that registers a Rewardshare
type MsgRegisterRewardshare struct {
	// contract hex address
	ContractAddress string `protobuf:"bytes,1,opt,name=contract_address,json=contractAddress,proto3" json:"contract_address,omitempty"`
	// bech32 address of message sender, must be the same as the origin EOA
	// sending the transaction which deploys the contract
	DeployerAddress string `protobuf:"bytes,2,opt,name=deployer_address,json=deployerAddress,proto3" json:"deployer_address,omitempty"`
	// bech32 address of account receiving the transaction fees
	WithdrawerAddress string `protobuf:"bytes,3,opt,name=withdrawer_address,json=withdrawerAddress,proto3" json:"withdrawer_address,omitempty"`
	// array of nonces from the address path, where the last nonce is the nonce
	// that determines the contract's address - it can be an EOA nonce or a
	// factory contract nonce
	Nonces []uint64 `protobuf:"varint,4,rep,packed,name=nonces,proto3" json:"nonces,omitempty"`
}

func (m *MsgRegisterRewardshare) Reset()         { *m = MsgRegisterRewardshare{} }
func (m *MsgRegisterRewardshare) String() string { return proto.CompactTextString(m) }
func (*MsgRegisterRewardshare) ProtoMessage()    {}
func (*MsgRegisterRewardshare) Descriptor() ([]byte, []int) {
	return fileDescriptor_585499783d09e2e5, []int{0}
}
func (m *MsgRegisterRewardshare) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRegisterRewardshare) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRegisterRewardshare.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRegisterRewardshare) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRegisterRewardshare.Merge(m, src)
}
func (m *MsgRegisterRewardshare) XXX_Size() int {
	return m.Size()
}
func (m *MsgRegisterRewardshare) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRegisterRewardshare.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRegisterRewardshare proto.InternalMessageInfo

func (m *MsgRegisterRewardshare) GetContractAddress() string {
	if m != nil {
		return m.ContractAddress
	}
	return ""
}

func (m *MsgRegisterRewardshare) GetDeployerAddress() string {
	if m != nil {
		return m.DeployerAddress
	}
	return ""
}

func (m *MsgRegisterRewardshare) GetWithdrawerAddress() string {
	if m != nil {
		return m.WithdrawerAddress
	}
	return ""
}

func (m *MsgRegisterRewardshare) GetNonces() []uint64 {
	if m != nil {
		return m.Nonces
	}
	return nil
}

// MsgRegisterRewardshareResponse defines the MsgRegisterRewardshare response type
type MsgRegisterRewardshareResponse struct {
}

func (m *MsgRegisterRewardshareResponse) Reset()         { *m = MsgRegisterRewardshareResponse{} }
func (m *MsgRegisterRewardshareResponse) String() string { return proto.CompactTextString(m) }
func (*MsgRegisterRewardshareResponse) ProtoMessage()    {}
func (*MsgRegisterRewardshareResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_585499783d09e2e5, []int{1}
}
func (m *MsgRegisterRewardshareResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRegisterRewardshareResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRegisterRewardshareResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRegisterRewardshareResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRegisterRewardshareResponse.Merge(m, src)
}
func (m *MsgRegisterRewardshareResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgRegisterRewardshareResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRegisterRewardshareResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRegisterRewardshareResponse proto.InternalMessageInfo

// MsgUpdateRewardshare defines a message that updates the withdrawer address for a
// registered Rewardshare
type MsgUpdateRewardshare struct {
	// contract hex address
	ContractAddress string `protobuf:"bytes,1,opt,name=contract_address,json=contractAddress,proto3" json:"contract_address,omitempty"`
	// deployer bech32 address
	DeployerAddress string `protobuf:"bytes,2,opt,name=deployer_address,json=deployerAddress,proto3" json:"deployer_address,omitempty"`
	// new withdrawer bech32 address for receiving the transaction fees
	WithdrawerAddress string `protobuf:"bytes,3,opt,name=withdrawer_address,json=withdrawerAddress,proto3" json:"withdrawer_address,omitempty"`
}

func (m *MsgUpdateRewardshare) Reset()         { *m = MsgUpdateRewardshare{} }
func (m *MsgUpdateRewardshare) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateRewardshare) ProtoMessage()    {}
func (*MsgUpdateRewardshare) Descriptor() ([]byte, []int) {
	return fileDescriptor_585499783d09e2e5, []int{2}
}
func (m *MsgUpdateRewardshare) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateRewardshare) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateRewardshare.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateRewardshare) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateRewardshare.Merge(m, src)
}
func (m *MsgUpdateRewardshare) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateRewardshare) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateRewardshare.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateRewardshare proto.InternalMessageInfo

func (m *MsgUpdateRewardshare) GetContractAddress() string {
	if m != nil {
		return m.ContractAddress
	}
	return ""
}

func (m *MsgUpdateRewardshare) GetDeployerAddress() string {
	if m != nil {
		return m.DeployerAddress
	}
	return ""
}

func (m *MsgUpdateRewardshare) GetWithdrawerAddress() string {
	if m != nil {
		return m.WithdrawerAddress
	}
	return ""
}

// MsgUpdateRewardshareResponse defines the MsgUpdateRewardshare response type
type MsgUpdateRewardshareResponse struct {
}

func (m *MsgUpdateRewardshareResponse) Reset()         { *m = MsgUpdateRewardshareResponse{} }
func (m *MsgUpdateRewardshareResponse) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateRewardshareResponse) ProtoMessage()    {}
func (*MsgUpdateRewardshareResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_585499783d09e2e5, []int{3}
}
func (m *MsgUpdateRewardshareResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateRewardshareResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateRewardshareResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateRewardshareResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateRewardshareResponse.Merge(m, src)
}
func (m *MsgUpdateRewardshareResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateRewardshareResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateRewardshareResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateRewardshareResponse proto.InternalMessageInfo

// MsgCancelRewardshare defines a message that cancels a registered Rewardshare
type MsgCancelRewardshare struct {
	// contract hex address
	ContractAddress string `protobuf:"bytes,1,opt,name=contract_address,json=contractAddress,proto3" json:"contract_address,omitempty"`
	// deployer bech32 address
	DeployerAddress string `protobuf:"bytes,2,opt,name=deployer_address,json=deployerAddress,proto3" json:"deployer_address,omitempty"`
}

func (m *MsgCancelRewardshare) Reset()         { *m = MsgCancelRewardshare{} }
func (m *MsgCancelRewardshare) String() string { return proto.CompactTextString(m) }
func (*MsgCancelRewardshare) ProtoMessage()    {}
func (*MsgCancelRewardshare) Descriptor() ([]byte, []int) {
	return fileDescriptor_585499783d09e2e5, []int{4}
}
func (m *MsgCancelRewardshare) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCancelRewardshare) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCancelRewardshare.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCancelRewardshare) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCancelRewardshare.Merge(m, src)
}
func (m *MsgCancelRewardshare) XXX_Size() int {
	return m.Size()
}
func (m *MsgCancelRewardshare) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCancelRewardshare.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCancelRewardshare proto.InternalMessageInfo

func (m *MsgCancelRewardshare) GetContractAddress() string {
	if m != nil {
		return m.ContractAddress
	}
	return ""
}

func (m *MsgCancelRewardshare) GetDeployerAddress() string {
	if m != nil {
		return m.DeployerAddress
	}
	return ""
}

// MsgCancelRewardshareResponse defines the MsgCancelRewardshare response type
type MsgCancelRewardshareResponse struct {
}

func (m *MsgCancelRewardshareResponse) Reset()         { *m = MsgCancelRewardshareResponse{} }
func (m *MsgCancelRewardshareResponse) String() string { return proto.CompactTextString(m) }
func (*MsgCancelRewardshareResponse) ProtoMessage()    {}
func (*MsgCancelRewardshareResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_585499783d09e2e5, []int{5}
}
func (m *MsgCancelRewardshareResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCancelRewardshareResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCancelRewardshareResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCancelRewardshareResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCancelRewardshareResponse.Merge(m, src)
}
func (m *MsgCancelRewardshareResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgCancelRewardshareResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCancelRewardshareResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCancelRewardshareResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgRegisterRewardshare)(nil), "kynno.rewardshare.v1.MsgRegisterRewardshare")
	proto.RegisterType((*MsgRegisterRewardshareResponse)(nil), "kynno.rewardshare.v1.MsgRegisterRewardshareResponse")
	proto.RegisterType((*MsgUpdateRewardshare)(nil), "kynno.rewardshare.v1.MsgUpdateRewardshare")
	proto.RegisterType((*MsgUpdateRewardshareResponse)(nil), "kynno.rewardshare.v1.MsgUpdateRewardshareResponse")
	proto.RegisterType((*MsgCancelRewardshare)(nil), "kynno.rewardshare.v1.MsgCancelRewardshare")
	proto.RegisterType((*MsgCancelRewardshareResponse)(nil), "kynno.rewardshare.v1.MsgCancelRewardshareResponse")
}

func init() { proto.RegisterFile("kynno/rewardshare/v1/tx.proto", fileDescriptor_585499783d09e2e5) }

var fileDescriptor_585499783d09e2e5 = []byte{
	// 448 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x94, 0x3f, 0x8f, 0xd3, 0x30,
	0x14, 0xc0, 0xe3, 0x6b, 0x74, 0x12, 0x5e, 0xe0, 0x42, 0x75, 0x3a, 0x45, 0x87, 0xa9, 0x32, 0x1d,
	0x7f, 0x1a, 0xeb, 0xae, 0xb0, 0xb0, 0x01, 0x73, 0x96, 0x48, 0x2c, 0x2c, 0x27, 0x5f, 0xf2, 0xe4,
	0x46, 0x14, 0x3b, 0xb2, 0x7d, 0xd7, 0xeb, 0xca, 0x07, 0x40, 0x48, 0x7c, 0x01, 0xd8, 0x18, 0xd9,
	0xf9, 0x02, 0x8c, 0x95, 0x58, 0x18, 0x51, 0xcb, 0xc0, 0xc7, 0x40, 0x75, 0x9a, 0x34, 0x55, 0x12,
	0x54, 0x06, 0x24, 0x36, 0xe7, 0xbd, 0xdf, 0xb3, 0x7f, 0x2f, 0x7e, 0x09, 0xbe, 0xf3, 0x6a, 0x26,
	0x84, 0xa4, 0x0a, 0xa6, 0x4c, 0xa5, 0x7a, 0xcc, 0x14, 0xd0, 0xab, 0x53, 0x6a, 0xae, 0xc3, 0x5c,
	0x49, 0x23, 0xbd, 0xbe, 0x4d, 0x87, 0xb5, 0x74, 0x78, 0x75, 0xea, 0x1f, 0x73, 0x29, 0xf9, 0x04,
	0x28, 0xcb, 0x33, 0xca, 0x84, 0x90, 0x86, 0x99, 0x4c, 0x0a, 0x5d, 0xd4, 0xf8, 0x7d, 0x2e, 0xb9,
	0xb4, 0x4b, 0xba, 0x5a, 0x15, 0xd1, 0xe0, 0x0b, 0xc2, 0x87, 0x91, 0xe6, 0x31, 0xf0, 0x4c, 0x1b,
	0x50, 0xf1, 0x66, 0x47, 0xef, 0x1e, 0xbe, 0x95, 0x48, 0x61, 0x14, 0x4b, 0xcc, 0x39, 0x4b, 0x53,
	0x05, 0x5a, 0x1f, 0xa1, 0x01, 0x3a, 0xb9, 0x11, 0xdf, 0x2c, 0xe3, 0x4f, 0x8b, 0xf0, 0x0a, 0x4d,
	0x21, 0x9f, 0xc8, 0x19, 0xa8, 0x0a, 0xdd, 0x2b, 0xd0, 0x32, 0x5e, 0xa2, 0x43, 0xec, 0x4d, 0x33,
	0x33, 0x4e, 0x15, 0x9b, 0xd6, 0xe0, 0x9e, 0x85, 0x0f, 0x36, 0x99, 0x12, 0x3f, 0xc4, 0xfb, 0x42,
	0x8a, 0x04, 0xf4, 0x91, 0x3b, 0xe8, 0x9d, 0xb8, 0xf1, 0xfa, 0xe9, 0x89, 0xfb, 0xeb, 0xc3, 0x5d,
	0x27, 0x18, 0x60, 0xd2, 0x2e, 0x1f, 0x83, 0xce, 0xa5, 0xd0, 0x10, 0x7c, 0x44, 0xb8, 0x1f, 0x69,
	0xfe, 0x22, 0x4f, 0x99, 0x81, 0xff, 0xad, 0xbb, 0x75, 0x17, 0x04, 0x1f, 0xb7, 0x29, 0x56, 0x3d,
	0x28, 0xdb, 0xc2, 0x73, 0x26, 0x12, 0x98, 0xfc, 0xf3, 0x16, 0xb6, 0x9c, 0x1a, 0x67, 0x96, 0x4e,
	0x67, 0x6f, 0x5d, 0xdc, 0x8b, 0x34, 0xf7, 0x3e, 0x23, 0x7c, 0xbb, 0x6d, 0x78, 0x1e, 0x86, 0x6d,
	0x23, 0x1a, 0xb6, 0xdf, 0x96, 0xff, 0xe8, 0x6f, 0xe8, 0xea, 0xbd, 0x3c, 0x7e, 0xf3, 0xed, 0xe7,
	0xfb, 0x3d, 0x1a, 0x0c, 0x69, 0xc7, 0xd7, 0x42, 0xd5, 0xba, 0xfa, 0xbc, 0x96, 0xf2, 0x3e, 0x21,
	0x7c, 0xd0, 0x9c, 0x87, 0xfb, 0x9d, 0x0a, 0x0d, 0xd6, 0x3f, 0xdb, 0x9d, 0xad, 0x64, 0x47, 0x56,
	0x76, 0x18, 0x3c, 0xe8, 0x94, 0xbd, 0xb4, 0xb5, 0x0d, 0xd5, 0xe6, 0xbd, 0x77, 0xab, 0x36, 0xd8,
	0x3f, 0xa8, 0x76, 0xde, 0xed, 0x0e, 0xaa, 0x89, 0xad, 0xad, 0xab, 0x3e, 0x8b, 0xbe, 0x2e, 0x08,
	0x9a, 0x2f, 0x08, 0xfa, 0xb1, 0x20, 0xe8, 0xdd, 0x92, 0x38, 0xf3, 0x25, 0x71, 0xbe, 0x2f, 0x89,
	0xf3, 0x72, 0xc4, 0x33, 0x33, 0xbe, 0xbc, 0x08, 0x13, 0xf9, 0xba, 0xd8, 0x10, 0x84, 0x01, 0x95,
	0xab, 0x4c, 0x03, 0x4d, 0xa4, 0x02, 0x7a, 0xbd, 0x75, 0x82, 0x99, 0xe5, 0xa0, 0x2f, 0xf6, 0xed,
	0xef, 0x69, 0xf4, 0x3b, 0x00, 0x00, 0xff, 0xff, 0x51, 0x2f, 0x93, 0x45, 0x09, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	// RegisterRewardshare registers a new contract for receiving transaction fees
	RegisterRewardshare(ctx context.Context, in *MsgRegisterRewardshare, opts ...grpc.CallOption) (*MsgRegisterRewardshareResponse, error)
	// UpdateRewardshare updates the withdrawer address of a rewardshare
	UpdateRewardshare(ctx context.Context, in *MsgUpdateRewardshare, opts ...grpc.CallOption) (*MsgUpdateRewardshareResponse, error)
	// CancelRewardshare cancels a contract's fee registration and further receival
	// of transaction fees
	CancelRewardshare(ctx context.Context, in *MsgCancelRewardshare, opts ...grpc.CallOption) (*MsgCancelRewardshareResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) RegisterRewardshare(ctx context.Context, in *MsgRegisterRewardshare, opts ...grpc.CallOption) (*MsgRegisterRewardshareResponse, error) {
	out := new(MsgRegisterRewardshareResponse)
	err := c.cc.Invoke(ctx, "/kynno.rewardshare.v1.Msg/RegisterRewardshare", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) UpdateRewardshare(ctx context.Context, in *MsgUpdateRewardshare, opts ...grpc.CallOption) (*MsgUpdateRewardshareResponse, error) {
	out := new(MsgUpdateRewardshareResponse)
	err := c.cc.Invoke(ctx, "/kynno.rewardshare.v1.Msg/UpdateRewardshare", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) CancelRewardshare(ctx context.Context, in *MsgCancelRewardshare, opts ...grpc.CallOption) (*MsgCancelRewardshareResponse, error) {
	out := new(MsgCancelRewardshareResponse)
	err := c.cc.Invoke(ctx, "/kynno.rewardshare.v1.Msg/CancelRewardshare", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	// RegisterRewardshare registers a new contract for receiving transaction fees
	RegisterRewardshare(context.Context, *MsgRegisterRewardshare) (*MsgRegisterRewardshareResponse, error)
	// UpdateRewardshare updates the withdrawer address of a rewardshare
	UpdateRewardshare(context.Context, *MsgUpdateRewardshare) (*MsgUpdateRewardshareResponse, error)
	// CancelRewardshare cancels a contract's fee registration and further receival
	// of transaction fees
	CancelRewardshare(context.Context, *MsgCancelRewardshare) (*MsgCancelRewardshareResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) RegisterRewardshare(ctx context.Context, req *MsgRegisterRewardshare) (*MsgRegisterRewardshareResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterRewardshare not implemented")
}
func (*UnimplementedMsgServer) UpdateRewardshare(ctx context.Context, req *MsgUpdateRewardshare) (*MsgUpdateRewardshareResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateRewardshare not implemented")
}
func (*UnimplementedMsgServer) CancelRewardshare(ctx context.Context, req *MsgCancelRewardshare) (*MsgCancelRewardshareResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelRewardshare not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_RegisterRewardshare_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgRegisterRewardshare)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).RegisterRewardshare(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kynno.rewardshare.v1.Msg/RegisterRewardshare",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).RegisterRewardshare(ctx, req.(*MsgRegisterRewardshare))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_UpdateRewardshare_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateRewardshare)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateRewardshare(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kynno.rewardshare.v1.Msg/UpdateRewardshare",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateRewardshare(ctx, req.(*MsgUpdateRewardshare))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_CancelRewardshare_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgCancelRewardshare)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).CancelRewardshare(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kynno.rewardshare.v1.Msg/CancelRewardshare",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).CancelRewardshare(ctx, req.(*MsgCancelRewardshare))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "kynno.rewardshare.v1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterRewardshare",
			Handler:    _Msg_RegisterRewardshare_Handler,
		},
		{
			MethodName: "UpdateRewardshare",
			Handler:    _Msg_UpdateRewardshare_Handler,
		},
		{
			MethodName: "CancelRewardshare",
			Handler:    _Msg_CancelRewardshare_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "kynno/rewardshare/v1/tx.proto",
}

func (m *MsgRegisterRewardshare) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRegisterRewardshare) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRegisterRewardshare) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Nonces) > 0 {
		dAtA2 := make([]byte, len(m.Nonces)*10)
		var j1 int
		for _, num := range m.Nonces {
			for num >= 1<<7 {
				dAtA2[j1] = uint8(uint64(num)&0x7f | 0x80)
				num >>= 7
				j1++
			}
			dAtA2[j1] = uint8(num)
			j1++
		}
		i -= j1
		copy(dAtA[i:], dAtA2[:j1])
		i = encodeVarintTx(dAtA, i, uint64(j1))
		i--
		dAtA[i] = 0x22
	}
	if len(m.WithdrawerAddress) > 0 {
		i -= len(m.WithdrawerAddress)
		copy(dAtA[i:], m.WithdrawerAddress)
		i = encodeVarintTx(dAtA, i, uint64(len(m.WithdrawerAddress)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.DeployerAddress) > 0 {
		i -= len(m.DeployerAddress)
		copy(dAtA[i:], m.DeployerAddress)
		i = encodeVarintTx(dAtA, i, uint64(len(m.DeployerAddress)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.ContractAddress) > 0 {
		i -= len(m.ContractAddress)
		copy(dAtA[i:], m.ContractAddress)
		i = encodeVarintTx(dAtA, i, uint64(len(m.ContractAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgRegisterRewardshareResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRegisterRewardshareResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRegisterRewardshareResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgUpdateRewardshare) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateRewardshare) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateRewardshare) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.WithdrawerAddress) > 0 {
		i -= len(m.WithdrawerAddress)
		copy(dAtA[i:], m.WithdrawerAddress)
		i = encodeVarintTx(dAtA, i, uint64(len(m.WithdrawerAddress)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.DeployerAddress) > 0 {
		i -= len(m.DeployerAddress)
		copy(dAtA[i:], m.DeployerAddress)
		i = encodeVarintTx(dAtA, i, uint64(len(m.DeployerAddress)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.ContractAddress) > 0 {
		i -= len(m.ContractAddress)
		copy(dAtA[i:], m.ContractAddress)
		i = encodeVarintTx(dAtA, i, uint64(len(m.ContractAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgUpdateRewardshareResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateRewardshareResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateRewardshareResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgCancelRewardshare) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCancelRewardshare) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCancelRewardshare) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.DeployerAddress) > 0 {
		i -= len(m.DeployerAddress)
		copy(dAtA[i:], m.DeployerAddress)
		i = encodeVarintTx(dAtA, i, uint64(len(m.DeployerAddress)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.ContractAddress) > 0 {
		i -= len(m.ContractAddress)
		copy(dAtA[i:], m.ContractAddress)
		i = encodeVarintTx(dAtA, i, uint64(len(m.ContractAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgCancelRewardshareResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCancelRewardshareResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCancelRewardshareResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgRegisterRewardshare) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ContractAddress)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.DeployerAddress)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.WithdrawerAddress)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if len(m.Nonces) > 0 {
		l = 0
		for _, e := range m.Nonces {
			l += sovTx(uint64(e))
		}
		n += 1 + sovTx(uint64(l)) + l
	}
	return n
}

func (m *MsgRegisterRewardshareResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgUpdateRewardshare) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ContractAddress)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.DeployerAddress)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.WithdrawerAddress)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgUpdateRewardshareResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgCancelRewardshare) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ContractAddress)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.DeployerAddress)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgCancelRewardshareResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgRegisterRewardshare) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRegisterRewardshare: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRegisterRewardshare: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ContractAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ContractAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DeployerAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DeployerAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field WithdrawerAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.WithdrawerAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType == 0 {
				var v uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowTx
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.Nonces = append(m.Nonces, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowTx
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthTx
				}
				postIndex := iNdEx + packedLen
				if postIndex < 0 {
					return ErrInvalidLengthTx
				}
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				var elementCount int
				var count int
				for _, integer := range dAtA[iNdEx:postIndex] {
					if integer < 128 {
						count++
					}
				}
				elementCount = count
				if elementCount != 0 && len(m.Nonces) == 0 {
					m.Nonces = make([]uint64, 0, elementCount)
				}
				for iNdEx < postIndex {
					var v uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowTx
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.Nonces = append(m.Nonces, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field Nonces", wireType)
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgRegisterRewardshareResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRegisterRewardshareResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRegisterRewardshareResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateRewardshare) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateRewardshare: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateRewardshare: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ContractAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ContractAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DeployerAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DeployerAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field WithdrawerAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.WithdrawerAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateRewardshareResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateRewardshareResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateRewardshareResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCancelRewardshare) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCancelRewardshare: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCancelRewardshare: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ContractAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ContractAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DeployerAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DeployerAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCancelRewardshareResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCancelRewardshareResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCancelRewardshareResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
